// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaslB909fV9HStZOb-hbckQEvCi0UrhLs',
    appId: '1:778611558680:web:19247b57b9cf1bec8f766d',
    messagingSenderId: '778611558680',
    projectId: 'carrental-b3fa4',
    authDomain: 'carrental-b3fa4.firebaseapp.com',
    storageBucket: 'carrental-b3fa4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtEwGsHmyPp_dHAO_y4IMvOhMsiEUgJEY',
    appId: '1:778611558680:android:d5371187f375c9fc8f766d',
    messagingSenderId: '778611558680',
    projectId: 'carrental-b3fa4',
    storageBucket: 'carrental-b3fa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdGv_IPXixNcQ9akYAc_TvGf7FRLDd5V8',
    appId: '1:778611558680:ios:e74487768b1b6be88f766d',
    messagingSenderId: '778611558680',
    projectId: 'carrental-b3fa4',
    storageBucket: 'carrental-b3fa4.appspot.com',
    iosBundleId: 'com.example.carrentalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdGv_IPXixNcQ9akYAc_TvGf7FRLDd5V8',
    appId: '1:778611558680:ios:e74487768b1b6be88f766d',
    messagingSenderId: '778611558680',
    projectId: 'carrental-b3fa4',
    storageBucket: 'carrental-b3fa4.appspot.com',
    iosBundleId: 'com.example.carrentalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaslB909fV9HStZOb-hbckQEvCi0UrhLs',
    appId: '1:778611558680:web:05943f555b5dff4d8f766d',
    messagingSenderId: '778611558680',
    projectId: 'carrental-b3fa4',
    authDomain: 'carrental-b3fa4.firebaseapp.com',
    storageBucket: 'carrental-b3fa4.appspot.com',
  );

}